# Project-wide Gradle settings.
# https://docs.gradle.org/current/userguide/build_environment.html

# ─── JVM ──────────────────────────────────────────────────────────────────────
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8

# ─── Build performance ────────────────────────────────────────────────────────
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true

# ─── Kotlin ───────────────────────────────────────────────────────────────────
kotlin.code.style=official
kotlin.incremental=true

# ─── AndroidX ────────────────────────────────────────────────────────────────
android.useAndroidX=true
android.nonTransitiveRClass=true
